spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-restful-springboot-aws-db?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
          show-sql: true
          format_sql: true
  jackson:
    default-property-inclusion: non-null
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG    
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
