spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-restful-springboot-aws-db?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
